import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ApolloProvider } from "@apollo/client";
import { ReduxProvider } from "@/src/redux/provider";
import { client } from "@/utils/apolloClient";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ApolloProvider client={client}>
          <ReduxProvider>{children}</ReduxProvider>
        </ApolloProvider>
      </body>
    </html>
  );
}
